package org.drakon.drakonchat;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

public class MainActivity extends Activity {
    LinearLayout root;
    String email="", role="";
    JSONObject users, chats;
    SharedPreferences prefs;
    int themeIndex=0;
    final int[] BG={Color.rgb(12,7,22),Color.rgb(8,12,24),Color.rgb(8,20,18),Color.rgb(24,13,8)};
    final int[] CARD={Color.rgb(32,18,55),Color.rgb(18,29,52),Color.rgb(15,40,35),Color.rgb(48,25,14)};
    final int[] ACCENT={Color.rgb(177,86,255),Color.rgb(70,150,255),Color.rgb(54,205,145),Color.rgb(225,155,62)};
    final int TXT=Color.rgb(246,243,252), MUTED=Color.rgb(190,181,207), GOLD=Color.rgb(246,196,77);
    final int PICK_AVATAR=7001;

    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        prefs=getSharedPreferences("db",0); themeIndex=prefs.getInt("theme",0);
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);
        applyBars(); users=loadObject("users"); chats=loadObject("chats"); ensureAdmin(); showLogin();
    }
    void applyBars(){getWindow().setStatusBarColor(BG[themeIndex]);getWindow().setNavigationBarColor(BG[themeIndex]);}
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextColor(TXT);t.setTextSize(sp);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(16),dp(10),dp(16),dp(10));return t;}
    EditText input(String hint,boolean pass){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(125,116,140));e.setTextColor(TXT);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setBackground(round(Color.rgb(24,16,36),dp(14)));if(pass)e.setInputType(0x81);else e.setInputType(0x21);return e;}
    GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);g.setStroke(dp(1),Color.argb(70,255,255,255));return g;}
    GradientDrawable gradient(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{BG[themeIndex],CARD[themeIndex],Color.rgb(Math.min(255,BG[themeIndex]/1+18),Math.min(255,BG[themeIndex]/1+8),Math.min(255,BG[themeIndex]/1+28))});g.setCornerRadius(0);return g;}
    Button btn(String text){Button b=new Button(this);b.setText(text);b.setTextColor(TXT);b.setTextSize(15);b.setAllCaps(false);b.setMinHeight(dp(54));b.setPadding(dp(8),0,dp(8),0);b.setBackground(round(CARD[themeIndex],dp(15)));return b;}
    TextView section(String s){TextView t=tv(s,17);t.setTypeface(null,Typeface.BOLD);t.setTextColor(GOLD);return t;}
    void base(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackground(gradient());root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(16),dp(14),dp(16),dp(18));sc.addView(root,new ScrollView.LayoutParams(-1,-1));setContentView(sc);applyBars();}
    void add(View v,int h){root.addView(v,new LinearLayout.LayoutParams(-1,dp(h)));}
    void addWrap(View v){root.addView(v,new LinearLayout.LayoutParams(-1,-2));}

    TextView title(String s){TextView t=tv(s,27);t.setTypeface(null,Typeface.BOLD);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTextColor(TXT);return t;}
    void topBar(String name,View.OnClickListener back){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(0,0,0,dp(5));Button b=btn("‹");b.setTextSize(28);bar.addView(b,new LinearLayout.LayoutParams(dp(58),dp(55)));TextView t=title(name);bar.addView(t,new LinearLayout.LayoutParams(0,dp(55),1));root.addView(bar);b.setOnClickListener(back);}

    void showLogin(){base();add(new Space(this),20);ImageView im=new ImageView(this);im.setImageResource(R.drawable.deewan);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);add(im,145);TextView logo=tv("DRAGON CHAT",30);logo.setGravity(Gravity.CENTER);logo.setTypeface(null,Typeface.BOLD);logo.setTextColor(ACCENT[themeIndex]);add(logo,55);add(tv("منصة اجتماعية بتصميم جديد",15),42);EditText e=input("البريد الإلكتروني",false),p=input("كلمة السر",true);add(e,58);add(p,58);Button login=btn("دخول إلى الحساب");add(login,60);login.setOnClickListener(v->login(e.getText().toString().trim(),p.getText().toString()));Button reg=btn("إنشاء حساب جديد");add(reg,60);reg.setOnClickListener(v->showRegister());Button th=btn("🎨 مظهر التطبيق");add(th,56);th.setOnClickListener(v->themeDialog());}

    void showRegister(){base();topBar("إنشاء حساب جديد",v->showLogin());add(tv("أنشئ هويتك داخل Dragon Chat",18),50);EditText e=input("البريد الإلكتروني",false),p=input("كلمة السر - 6 أحرف على الأقل",true),c=input("تأكيد كلمة السر",true);add(e,58);add(p,58);add(c,58);Button b=btn("إنشاء الحساب");add(b,62);b.setOnClickListener(v->{String em=e.getText().toString().trim(),pw=p.getText().toString(),cf=c.getText().toString();if(!em.contains("@")||pw.length()<6||!pw.equals(cf)){notice("تحقق من البيانات وكلمة السر.");return;}try{if(users.has(em)){notice("الحساب موجود مسبقاً.");return;}String[] h=hash(pw,null);JSONObject u=new JSONObject();u.put("email",em);u.put("password_salt",h[0]);u.put("password_hash",h[1]);u.put("role","member");u.put("coins",0);u.put("level",1);u.put("active",true);u.put("id",newUserId());u.put("name",em.substring(0,em.indexOf('@')));u.put("bio","أهلاً بكم في Dragon Chat");u.put("specialIdAllowed",false);u.put("avatar","");users.put(em,u);save();notice("تم إنشاء الحساب. رقم العضوية: "+u.optString("id"));showLogin();}catch(Exception x){notice("حدث خطأ.");}});}
    void login(String em,String pw){try{if(!users.has(em)){notice("الحساب غير موجود.");return;}JSONObject u=users.getJSONObject(em);if(!u.optBoolean("active",true)){notice("الحساب غير نشط.");return;}if(!verify(pw,u.getString("password_salt"),u.getString("password_hash"))){notice("البريد أو كلمة السر غير صحيحة.");return;}email=em;role=u.optString("role","member");ensureUserFields(u);save();showHome();}catch(Exception x){notice("حدث خطأ.");}}

    String levelName(int level){String[] n={"مبتدئ","عضو","عضو نشط","متقدم","محترف","VIP","VIP Plus","نجم","أسطورة","نخبة"};if(level>=1&&level<=n.length)return n[level-1];return level==99?"مدير":"مستوى "+level;}
    View avatar(String em,int size){ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setClipToOutline(true);GradientDrawable bg=round(ACCENT[themeIndex],dp(size/2));bg.setShape(GradientDrawable.OVAL);im.setBackground(bg);try{String a=users.getJSONObject(em).optString("avatar","");if(!a.isEmpty())im.setImageURI(Uri.parse(a));else im.setImageResource(R.drawable.deewan);}catch(Exception e){im.setImageResource(R.drawable.deewan);}return im;}
    TextView pill(String s){TextView t=tv(s,14);t.setGravity(Gravity.CENTER);t.setTypeface(null,Typeface.BOLD);t.setBackground(round(ACCENT[themeIndex],dp(18)));return t;}

    void showHome(){base();try{JSONObject u=users.getJSONObject(email);ensureUserFields(u);int lv=u.optInt("level",1);add(tv("DRAGON CHAT",26),58);add(tv("مساحتك الاجتماعية الجديدة",14),38);LinearLayout nav=new LinearLayout(this);nav.setPadding(0,dp(4),0,dp(8));String[] ns={"⚔ المعركة","🎮 الألعاب","👥 الأصدقاء","💬 المجلس","🎁 الأحداث"};for(String n:ns){Button q=btn(n);q.setTextSize(13);nav.addView(q,new LinearLayout.LayoutParams(0,dp(58),1));if(n.contains("الأصدقاء"))q.setOnClickListener(v->showFriends());else if(n.contains("المجلس"))q.setOnClickListener(v->showChatList());else if(n.contains("المعركة"))q.setOnClickListener(v->simple("المعركة","ساحات التحدي والمنافسات قيد التطوير."));else if(n.contains("الألعاب"))q.setOnClickListener(v->simple("الألعاب","الألعاب المصغرة ستضاف هنا."));else q.setOnClickListener(v->showGifts());}addWrap(nav);
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(16),dp(18),dp(16));card.setBackground(round(CARD[themeIndex],dp(22)));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(avatar(email,92),new LinearLayout.LayoutParams(dp(92),dp(92)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setGravity(Gravity.RIGHT);TextView name=tv(u.optString("name","عضو"),22);name.setTypeface(null,Typeface.BOLD);info.addView(name,new LinearLayout.LayoutParams(-1,dp(34)));info.addView(tv("ID: "+u.optString("id"),14),new LinearLayout.LayoutParams(-1,dp(30)));TextView lvT=tv("LV "+lv+" • "+levelName(lv),15);lvT.setTextColor(GOLD);info.addView(lvT,new LinearLayout.LayoutParams(-1,dp(30)));row.addView(info,new LinearLayout.LayoutParams(0,dp(100),1));card.addView(row);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress(Math.min(100,lv*10));pb.setProgressTintList(android.content.res.ColorStateList.valueOf(ACCENT[themeIndex]));card.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(8),0,0);TextView coins=pill("💎 "+u.optInt("coins",0));TextView rank=pill("✦ "+(u.optString("role").equals("admin")?"مدير":levelName(lv)));stats.addView(coins,new LinearLayout.LayoutParams(0,dp(44),1));stats.addView(rank,new LinearLayout.LayoutParams(0,dp(44),1));card.addView(stats);root.addView(card,new LinearLayout.LayoutParams(-1,-2));
        Button profile=btn("👤 الملف الشخصي");add(profile,60);profile.setOnClickListener(v->showProfile(email));Button chat=btn("💬 الرسائل والدردشة");add(chat,60);chat.setOnClickListener(v->showChatList());Button vip=btn("✦ VIP والمزايا");add(vip,60);vip.setOnClickListener(v->simple("VIP","باقات ومزايا VIP.") );Button th=btn("🎨 الألوان والمظهر");add(th,56);th.setOnClickListener(v->themeDialog());if("admin".equals(role)){Button a=btn("👑 مركز الإدارة");add(a,62);a.setOnClickListener(v->showAdmin());}Button out=btn("تسجيل الخروج");add(out,58);out.setOnClickListener(v->{email="";role="";showLogin();});}catch(Exception ignored){}}

    void showProfile(String em){base();try{JSONObject u=users.getJSONObject(em);ensureUserFields(u);topBar("الملف الشخصي",v->{if(em.equals(email))showHome();else showChatList();});LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER_HORIZONTAL);hero.setPadding(dp(16),dp(14),dp(16),dp(18));hero.setBackground(round(CARD[themeIndex],dp(24)));hero.addView(avatar(em,116),new LinearLayout.LayoutParams(dp(116),dp(116)));TextView n=tv(u.optString("name","عضو"),25);n.setGravity(Gravity.CENTER);n.setTypeface(null,Typeface.BOLD);hero.addView(n,new LinearLayout.LayoutParams(-1,dp(45)));TextView id=tv("ID  •  "+u.optString("id"),15);id.setGravity(Gravity.CENTER);id.setTextColor(GOLD);hero.addView(id,new LinearLayout.LayoutParams(-1,dp(36)));TextView rank=tv("✦  "+("admin".equals(u.optString("role"))?"مدير النظام":levelName(u.optInt("level",1))),16);rank.setGravity(Gravity.CENTER);hero.addView(rank,new LinearLayout.LayoutParams(-1,dp(36)));addWrap(hero);
        LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(10),0,dp(10));String[] vals={"LV "+u.optInt("level",1),"💎 "+u.optInt("coins",0),"★ "+("admin".equals(u.optString("role"))?"ADMIN":"عضو")};for(String s:vals){TextView x=pill(s);stats.addView(x,new LinearLayout.LayoutParams(0,dp(52),1));}addWrap(stats);add(section("عن العضو"),45);add(tv(u.optString("bio","لا توجد نبذة"),16),70);add(section("معلومات الحساب"),45);add(tv("الحساب: "+em,15),48);if(!"admin".equals(u.optString("role")))add(tv("ID مميز: "+(u.optBoolean("specialIdAllowed",false)?"مسموح من المدير":"غير مسموح"),15),48);Button edit=btn("✎ تعديل الاسم والنبذة");add(edit,58);if(em.equals(email))edit.setOnClickListener(v->editProfile(em));else edit.setVisibility(View.GONE);Button photo=btn("📷 تغيير الصورة");add(photo,58);photo.setOnClickListener(v->pickAvatar(em));if(!em.equals(email)){Button c=btn("💬 فتح الدردشة");add(c,58);c.setOnClickListener(v->showChat(em));}Button back=btn("رجوع");add(back,58);back.setOnClickListener(v->{if(em.equals(email))showHome();else showChatList();});}catch(Exception e){notice("تعذر فتح الملف الشخصي.");}}

    void editProfile(String em){try{JSONObject u=users.getJSONObject(em);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(4),dp(8),0);EditText name=input("الاسم",false),bio=input("النبذة",false);name.setText(u.optString("name",""));bio.setText(u.optString("bio",""));box.addView(name,new LinearLayout.LayoutParams(-1,dp(58)));box.addView(bio,new LinearLayout.LayoutParams(-1,dp(58)));new AlertDialog.Builder(this).setTitle("تعديل الملف").setView(box).setPositiveButton("حفظ",(d,w)->{try{u.put("name",name.getText().toString().trim());u.put("bio",bio.getText().toString().trim());save();showProfile(em);}catch(Exception ignored){}}).setNegativeButton("إلغاء",null).show();}catch(Exception ignored){}}
    void pickAvatar(String em){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);prefs.edit().putString("pending_avatar_user",em).apply();startActivityForResult(i,PICK_AVATAR);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==PICK_AVATAR&&c==RESULT_OK&&data!=null&&data.getData()!=null){try{getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}String em=prefs.getString("pending_avatar_user",email);try{users.getJSONObject(em).put("avatar",data.getData().toString());save();showProfile(em);}catch(Exception ignored){}}}

    void showGifts(){base();topBar("الهدايا والفعاليات",v->showHome());add(tv("🎁 متجر الهدايا",23),52);add(tv("أرسل هدية مميزة للأصدقاء أو اجمعها في ملفك",14),42);String[][] gifts={{"🌹","وردة","25"},{"💎","ألماسة","100"},{"👑","تاج","500"},{"🚀","صاروخ","1000"},{"🏆","كأس البطولة","2500"},{"🐉","تنين Dragon","5000"}};for(String[] g:gifts){LinearLayout card=new LinearLayout(this);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(12),dp(8),dp(12),dp(8));card.setBackground(round(CARD[themeIndex],dp(18)));TextView icon=tv(g[0],34);icon.setGravity(Gravity.CENTER);card.addView(icon,new LinearLayout.LayoutParams(dp(60),dp(62)));TextView info=tv(g[1]+"\n💎 "+g[2]+" عملة",16);info.setTypeface(null,Typeface.BOLD);card.addView(info,new LinearLayout.LayoutParams(0,dp(62),1));Button send=btn("إرسال");card.addView(send,new LinearLayout.LayoutParams(dp(82),dp(54)));send.setOnClickListener(v->chooseGift(g[1],Integer.parseInt(g[2])));addWrap(card);}add(tv("✨ فعاليات",20),55);add(tv("المركز الأول • 10,000 💎\nالمركز الثاني • 5,000 💎\nالمركز الثالث • 2,500 💎",16),110);}
    void chooseGift(String gift,int cost){try{ArrayList<String> names=new ArrayList<>();ArrayList<String> emails=new ArrayList<>();Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();if(!em.equals(email)){JSONObject u=users.getJSONObject(em);names.add(u.optString("name","عضو"));emails.add(em);}}if(names.isEmpty()){notice("لا يوجد أعضاء لإرسال الهدية لهم.");return;}new AlertDialog.Builder(this).setTitle("إرسال "+gift).setItems(names.toArray(new String[0]),(d,w)->{try{JSONObject me=users.getJSONObject(email);int coins=me.optInt("coins",0);if(coins<cost){notice("رصيدك لا يكفي لهذه الهدية.");return;}me.put("coins",coins-cost);JSONObject target=users.getJSONObject(emails.get(w));target.put("receivedGifts",target.optInt("receivedGifts",0)+1);save();notice("تم إرسال "+gift+" إلى "+target.optString("name","العضو")+" 🎉");}catch(Exception e){notice("تعذر إرسال الهدية.");}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){notice("تعذر فتح قائمة الأصدقاء.");}}

    void showFriends(){base();topBar("الأصدقاء",v->showHome());add(tv("الأعضاء الموجودون على هذا الجهاز",14),40);try{Iterator<String>it=users.keys();boolean any=false;while(it.hasNext()){String em=it.next();if(em.equals(email))continue;JSONObject u=users.getJSONObject(em);ensureUserFields(u);any=true;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(5),dp(8),dp(5));row.addView(avatar(em,54),new LinearLayout.LayoutParams(dp(54),dp(54)));TextView info=tv(u.optString("name","عضو")+"\nID: "+u.optString("id"),14);row.addView(info,new LinearLayout.LayoutParams(0,dp(62),1));Button b=btn("فتح");row.addView(b,new LinearLayout.LayoutParams(dp(80),dp(54)));addWrap(row);b.setOnClickListener(v->showProfile(em));}if(!any)add(tv("لا يوجد أعضاء آخرون حالياً.",17),70);}catch(Exception ignored){} }

    void showChatList(){base();topBar("الرسائل",v->showHome());add(tv("اختر محادثة",15),40);try{Iterator<String>it=users.keys();boolean any=false;while(it.hasNext()){String em=it.next();if(em.equals(email))continue;JSONObject u=users.getJSONObject(em);ensureUserFields(u);any=true;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(5),dp(8),dp(5));row.setBackground(round(CARD[themeIndex],dp(16)));row.addView(avatar(em,58),new LinearLayout.LayoutParams(dp(58),dp(58)));TextView info=tv(u.optString("name","عضو")+"\nID: "+u.optString("id"),14);row.addView(info,new LinearLayout.LayoutParams(0,dp(68),1));Button b=btn("دردشة");row.addView(b,new LinearLayout.LayoutParams(dp(88),dp(54)));add(row,78);b.setOnClickListener(v->showChat(em));}if(!any)add(tv("أنشئ حساباً آخر على نفس الجهاز لتجربة الدردشة المحلية.",16),90);}catch(Exception ignored){} }

    void showChat(String target){try{JSONObject tu=users.getJSONObject(target);ensureUserFields(tu);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(12),dp(8),dp(12),dp(10));page.setBackground(gradient());LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹");head.addView(back,new LinearLayout.LayoutParams(dp(55),dp(55)));head.addView(avatar(target,50),new LinearLayout.LayoutParams(dp(50),dp(50)));TextView ht=tv(tu.optString("name","عضو")+"\nID: "+tu.optString("id"),15);head.addView(ht,new LinearLayout.LayoutParams(0,dp(58),1));Button pr=btn("ملف");head.addView(pr,new LinearLayout.LayoutParams(dp(70),dp(54)));page.addView(head);back.setOnClickListener(v->showChatList());pr.setOnClickListener(v->showProfile(target));
            ScrollView msgScroll=new ScrollView(this);msgScroll.setFillViewport(true);LinearLayout messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(4),dp(8),dp(4),dp(8));String key=chatKey(email,target);JSONArray arr=chats.optJSONArray(key);if(arr==null)arr=new JSONArray();for(int i=0;i<arr.length();i++){JSONObject m=arr.optJSONObject(i);if(m==null)continue;String who=m.optString("from");String text=m.optString("text");TextView bubble=tv(text,16);bubble.setPadding(dp(16),dp(12),dp(16),dp(12));bubble.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);bubble.setBackground(round(who.equals(email)?Color.rgb(95,42,150):CARD[themeIndex],dp(18)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*0.78f),dp(62));bp.gravity=who.equals(email)?Gravity.LEFT:Gravity.RIGHT;bp.setMargins(0,dp(5),0,dp(5));messages.addView(bubble,bp);}msgScroll.addView(messages);page.addView(msgScroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=new LinearLayout(this);composer.setGravity(Gravity.CENTER_VERTICAL);EditText msg=input("اكتب رسالتك...",false);composer.addView(msg,new LinearLayout.LayoutParams(0,dp(58),1));Button send=btn("إرسال");composer.addView(send,new LinearLayout.LayoutParams(dp(86),dp(58)));page.addView(composer);send.setOnClickListener(v->{String s=msg.getText().toString().trim();if(s.isEmpty())return;try{JSONArray a=chats.optJSONArray(key);if(a==null)a=new JSONArray();JSONObject m=new JSONObject();m.put("from",email);m.put("text",s);m.put("time",System.currentTimeMillis());a.put(m);chats.put(key,a);save();showChat(target);}catch(Exception ignored){}});setContentView(page);applyBars();msgScroll.post(()->msgScroll.fullScroll(View.FOCUS_DOWN));}catch(Exception e){notice("تعذر فتح الدردشة.");}}
    String chatKey(String a,String b){return a.compareTo(b)<0?a+"|"+b:b+"|"+a;}

    void showAdmin(){base();topBar("مركز الإدارة",v->showHome());try{JSONObject me=users.getJSONObject(email);ensureUserFields(me);add(tv("👑 إدارة أعضاء Dragon Chat",20),55);add(tv("ID المدير: "+me.optString("id"),15),45);Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();JSONObject u=users.getJSONObject(em);if(!"member".equals(u.optString("role")))continue;ensureUserFields(u);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(10),dp(8),dp(10),dp(8));card.setBackground(round(CARD[themeIndex],dp(18)));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(avatar(em,56),new LinearLayout.LayoutParams(dp(56),dp(56)));r.addView(tv(u.optString("name","عضو")+"\nID: "+u.optString("id")+"\n💎 "+u.optInt("coins",0)+" • LV "+u.optInt("level",1),13),new LinearLayout.LayoutParams(0,dp(70),1));card.addView(r);LinearLayout bs=new LinearLayout(this);String[] labels={"عملات","مستوى","هدية","سماح ID","ID مميز","الملف"};for(String s:labels){Button b=btn(s);bs.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));if(s.equals("عملات"))b.setOnClickListener(v->giveDialog(em));else if(s.equals("مستوى"))b.setOnClickListener(v->memberDialog(em));else if(s.equals("هدية"))b.setOnClickListener(v->adminGiftDialog(em));else if(s.equals("سماح ID"))b.setOnClickListener(v->toggleSpecialIdPermission(em));else if(s.equals("ID مميز"))b.setOnClickListener(v->specialIdDialog(em));else b.setOnClickListener(v->showProfile(em));}card.addView(bs);addWrap(card);}}catch(Exception ignored){}}

    void adminGiftDialog(String target){String[] gifts={"🌹 وردة - 25","💎 ألماسة - 100","👑 تاج - 500","🚀 صاروخ - 1000","🏆 كأس البطولة - 2500","🐉 تنين Dragon - 5000"};new AlertDialog.Builder(this).setTitle("إهداء للعضو").setItems(gifts,(d,w)->{try{String[] parts=gifts[w].split(" - ");int n=Integer.parseInt(parts[1]);JSONObject u=users.getJSONObject(target);u.put("coins",u.optInt("coins",0));u.put("receivedGifts",u.optInt("receivedGifts",0)+1);save();notice("تم إرسال "+parts[0]+" إلى "+u.optString("name","العضو")+" 🎉");showAdmin();}catch(Exception e){notice("تعذر إرسال الهدية.");}}).setNegativeButton("إلغاء",null).show();}
    void memberDialog(String target){try{JSONObject u=users.getJSONObject(target);int current=u.optInt("level",1);String[]items=new String[10];for(int i=0;i<10;i++)items[i]=(i+1)+". "+levelName(i+1);new AlertDialog.Builder(this).setTitle("تغيير المستوى").setSingleChoiceItems(items,Math.max(0,current-1),(d,w)->{try{u.put("level",w+1);save();d.dismiss();notice("تم تحديث المستوى.");showAdmin();}catch(Exception x){notice("تعذر التحديث.");}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){notice("تعذر فتح العضو.");}}
    void giveDialog(String target){final EditText amount=input("عدد العملات",false);new AlertDialog.Builder(this).setTitle("إعطاء عملات").setMessage("ID العضو: "+idOf(target)).setView(amount).setPositiveButton("إعطاء",(d,w)->{try{int n=Integer.parseInt(amount.getText().toString().trim());if(n<=0||n>1000000){notice("عدد العملات غير صالح.");return;}JSONObject u=users.getJSONObject(target);u.put("coins",u.optInt("coins",0)+n);save();notice("تمت إضافة "+n+" عملة.");showAdmin();}catch(Exception x){notice("اكتب عدداً صحيحاً.");}}).setNegativeButton("إلغاء",null).show();}
    String idOf(String em){try{return users.getJSONObject(em).optString("id");}catch(Exception e){return "";}}
    boolean idExists(String wanted,String exceptEmail){try{Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();if(em.equals(exceptEmail))continue;JSONObject u=users.getJSONObject(em);if(wanted.equalsIgnoreCase(u.optString("id","")))return true;}}catch(Exception ignored){}return false;}
    void toggleSpecialIdPermission(String target){try{JSONObject u=users.getJSONObject(target);boolean now=!u.optBoolean("specialIdAllowed",false);u.put("specialIdAllowed",now);save();notice(now?"تم السماح للعضو بالـID المميز.":"تم سحب صلاحية الـID المميز.");showAdmin();}catch(Exception e){notice("تعذر تغيير الصلاحية.");}}
    void specialIdDialog(String target){try{JSONObject u=users.getJSONObject(target);if(!u.optBoolean("specialIdAllowed",false)){notice("فعّل سماح ID أولاً لهذا العضو.");return;}EditText idInput=input("مثال: 1000 أو VIP777",false);idInput.setText(u.optString("id",""));new AlertDialog.Builder(this).setTitle("تعيين ID مميز").setMessage("العضو: "+u.optString("name","عضو")).setView(idInput).setPositiveButton("حفظ",(d,w)->{String wanted=idInput.getText().toString().trim();if(wanted.length()<3||wanted.length()>20||wanted.contains(" ")){notice("الـID من 3 إلى 20 حرفاً/رقماً وبدون مسافات.");return;}if(idExists(wanted,target)){notice("هذا الـID مستخدم من عضو آخر.");return;}try{u.put("id",wanted);save();notice("تم تعيين الـID: "+wanted);showAdmin();}catch(Exception x){notice("تعذر الحفظ.");}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){notice("تعذر فتح العضو.");}}

    void themeDialog(){String[] items={"🟣 بنفسجي Dragon (افتراضي)","🔵 أزرق ليلي","🟢 أخضر زمردي","🟠 ذهبي داكن"};new AlertDialog.Builder(this).setTitle("اختيار ألوان التطبيق").setSingleChoiceItems(items,themeIndex,(d,w)->{themeIndex=w;prefs.edit().putInt("theme",themeIndex).apply();applyBars();d.dismiss();if(email.isEmpty())showLogin();else showHome();}).setNegativeButton("إلغاء",null).show();}
    void simple(String title,String body){base();topBar(title,v->showHome());add(tv(body,17),130);Button b=btn("رجوع");add(b,58);b.setOnClickListener(v->showHome());}

    void ensureAdmin(){try{if(!users.has("admin@drakon.com")){String[]h=hash("Admin123",null);JSONObject u=new JSONObject();u.put("email","admin@drakon.com");u.put("password_salt",h[0]);u.put("password_hash",h[1]);u.put("role","admin");u.put("coins",0);u.put("level",99);u.put("active",true);u.put("id","ADM-100001");u.put("name","المدير");u.put("bio","مدير Dragon Chat");u.put("avatar","");users.put("admin@drakon.com",u);save();}else{ensureUserFields(users.getJSONObject("admin@drakon.com"));save();}}catch(Exception ignored){}}
    void ensureUserFields(JSONObject u)throws Exception{if(!u.has("id"))u.put("id",newUserId());if(!u.has("name"))u.put("name",u.optString("email","عضو"));if(!u.has("bio"))u.put("bio","");if(!u.has("specialIdAllowed"))u.put("specialIdAllowed",false);if(!u.has("coins"))u.put("coins",0);if(!u.has("level"))u.put("level",1);if(!u.has("avatar"))u.put("avatar","");}
    String newUserId(){long n=System.currentTimeMillis()%1000000000L;int r=new SecureRandom().nextInt(900)+100;return "DRK-"+n+"-"+r;}
    JSONObject loadObject(String key){try{return new JSONObject(prefs.getString(key,"{}"));}catch(Exception e){return new JSONObject();}}
    void save(){prefs.edit().putString("users",users.toString()).putString("chats",chats.toString()).apply();}
    void notice(String s){new AlertDialog.Builder(this).setTitle("Dragon Chat").setMessage(s).setPositiveButton("حسناً",null).show();}
    String[] hash(String password,String salt)throws Exception{if(salt==null){byte[]b=new byte[16];new SecureRandom().nextBytes(b);salt=Base64.getEncoder().encodeToString(b);}PBEKeySpec spec=new PBEKeySpec(password.toCharArray(),salt.getBytes(StandardCharsets.UTF_8),120000,256);byte[]d=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();return new String[]{salt,Base64.getEncoder().encodeToString(d)};}
    boolean verify(String p,String s,String d)throws Exception{return MessageDigest.isEqual(hash(p,s)[1].getBytes(StandardCharsets.UTF_8),d.getBytes(StandardCharsets.UTF_8));}
}
